### ISSUE TITLE
java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper

### ISSUE THREAD

**Issue by ghost** [ChemAxon/marvinjs-docker-example#3]
If we use the docker file as in this example, we get the following error:
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is com.google.common.util.concurrent.ExecutionError: java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper] with root cause

java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
        at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807) ~[na:1.8.0_181]
        at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886) ~[na:1.8.0_181]
        at java.awt.Toolkit.getEventQueue(Toolkit.java:1736) ~[na:1.8.0_181]
        at java.awt.EventQueue.isDispatchThread(EventQueue.java:1071) ~[na:1.8.0_181]
        at javax.swing.SwingUtilities.isEventDispatchThread(SwingUtilities.java:1366) ~[na:1.8.0_181]
        at javax.swing.text.StyleContext.reclaim(StyleContext.java:454) ~[na:1.8.0_181]
        at javax.swing.text.StyleContext.addAttribute(StyleContext.java:311) ~[na:1.8.0_181]
        at javax.swing.text.StyleContext$NamedStyle.addAttribute(StyleContext.java:1501) ~[na:1.8.0_181]
        at javax.swing.text.StyleContext$NamedStyle.setName(StyleContext.java:1312) ~[na:1.8.0_181]
        at javax.swing.text.StyleContext$NamedStyle.<init>(StyleContext.java:1259) ~[na:1.8.0_181]
        at javax.swing.text.StyleContext.addStyle(StyleContext.java:107) ~[na:1.8.0_181]
        at javax.swing.text.StyleContext.<init>(StyleContext.java:87) ~[na:1.8.0_181]
        at javax.swing.text.DefaultStyledDocument.<init>(DefaultStyledDocument.java:106) ~[na:1.8.0_181]
        at chemaxon.common.util.tex.AbstractTeXDocument.<init>(AbstractTeXDocument.java:54) ~[common-19.21.0-10571.jar!/:19.21.0-10571]
        at chemaxon.common.util.tex.simpletex.SimpleTeXDocument.<init>(SimpleTeXDocument.java:40) ~[common-19.21.0-10571.jar!/:19.21.0-10571]
        at chemaxon.marvin.paint.internal.texgraphics.CachableTeXGraphics.<init>(CachableTeXGraphics.java:18) ~[marvin-gui-19.21.0-10571.jar!/:19.21.0-10571]
        at chemaxon.marvin.paint.internal.texgraphics.TeXGraphicsFactory.createGraphics(TeXGraphicsFactory.java:52) ~[marvin-gui-19.21.0-10571.jar!/:19.21.0-10571]
        at chemaxon.marvin.paint.internal.texgraphics.TeXGraphicsFactory.access$000(TeXGraphicsFactory.java:17) ~[marvin-gui-19.21.0-10571.jar!/:19.21.0-10571]
        at chemaxon.marvin.paint.internal.texgraphics.TeXGraphicsFactory$1.load(TeXGraphicsFactory.java:46) ~[marvin-gui-19.21.0-10571.jar!/:19.21.0-10571]
        at chemaxon.marvin.paint.internal.texgraphics.TeXGraphicsFactory$1.load(TeXGraphicsFactory.java:42) ~[marvin-gui-19.21.0-10571.jar!/:19.21.0-10571]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708) ~[guava-23.4-jre.jar!/:na]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416) ~[guava-23.4-jre.jar!/:na]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299) ~[guava-23.4-jre.jar!/:na]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212) ~[guava-23.4-jre.jar!/:na]
        at com.google.common.cache.LocalCache.get(LocalCache.java:4147) ~[guava-23.4-jre.jar!/:na]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151) ~[guava-23.4-jre.jar!/:na]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140) ~[guava-23.4-jre.jar!/:na]
        at chemaxon.marvin.paint.internal.texgraphics.TeXGraphicsFactory.getTeXGraphics(TeXGraphicsFactory.java:31) ~[marvin-gui-19.21.0-10571.jar!/:19.21.0-10571]
        at chemaxon.marvin.paint.internal.bounds.AtomBoundCalculator.appendAtomLabelBounds(AtomBoundCalculator.java:165) ~[marvin-gui-19.21.0-10571.jar!/:19.21.0-10571]
        at chemaxon.marvin.paint.internal.bounds.AtomBoundCalculator.getBounds(AtomBoundCalculator.java:85) ~[marvin-gui-19.21.0-10571.jar!/:19.21.0-10571]
        at chemaxon.marvin.paint.internal.bounds.BoundCalculator.calcAtomBounds(BoundCalculator.java:408) ~[marvin-gui-19.21.0-10571.jar!/:19.21.0-10571]
        at chemaxon.marvin.paint.internal.bounds.BoundCalculator.calcBounds(BoundCalculator.java:177) ~[marvin-gui-19.21.0-10571.jar!/:19.21.0-10571]
        at chemaxon.marvin.paint.internal.bounds.BoundCalculator.calcBounds(BoundCalculator.java:142) ~[marvin-gui-19.21.0-10571.jar!/:19.21.0-10571]
        at chemaxon.marvin.paint.internal.bounds.DefaultMoleculeBoundProvider.getNotNullBounds(DefaultMoleculeBoundProvider.java:185) ~[marvin-gui-19.21.0-10571.jar!/:19.21.0-10571]
        at chemaxon.marvin.paint.internal.bounds.DefaultMoleculeBoundProvider.updateTransform(DefaultMoleculeBoundProvider.java:157) ~[marvin-gui-19.21.0-10571.jar!/:19.21.0-10571]
        at chemaxon.marvin.paint.internal.bounds.DefaultMoleculeBoundProvider.setBoundsFor(DefaultMoleculeBoundProvider.java:252) ~[marvin-gui-19.21.0-10571.jar!/:19.21.0-10571]
        at chemaxon.marvin.paint.internal.MolPainter.setBoundsFor(MolPainter.java:705) ~[marvin-gui-19.21.0-10571.jar!/:19.21.0-10571]
        at chemaxon.marvin.io.image.exporter.ImageExport.initPainter(ImageExport.java:1030) ~[marvin-gui-19.21.0-10571.jar!/:19.21.0-10571]
        at chemaxon.marvin.io.formats.vectgraphics.SvgExport.convert(SvgExport.java:119) ~[marvin-gui-19.21.0-10571.jar!/:19.21.0-10571]
        at chemaxon.formats.MolExporter.exportToString(MolExporter.java:1385) ~[io-19.21.0-10571.jar!/:19.21.0-10571]
        at chemaxon.formats.MolExporter.exportToObject(MolExporter.java:1344) ~[io-19.21.0-10571.jar!/:19.21.0-10571]
        at chemaxon.formats.MolExporter.exportToObject(MolExporter.java:1288) ~[io-19.21.0-10571.jar!/:19.21.0-10571]
        at com.chemaxon.webservices.core.implementation.MolConvertService.convert(MolConvertService.java:53) ~[webservices-base-lib-19.21.0-10571.jar!/:19.21.0-10571]
        at com.chemaxon.webservices.controller.CalculateController.convertMolecule(CalculateController.java:65) ~[webservices-base-service-19.21.0-10571.jar!/:19.21.0-10571]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.13.jar!/:9.0.13]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90) ~[spring-boot-actuator-2.1.1.RELEASE.jar!/:2.1.1.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117) ~[spring-boot-actuator-2.1.1.RELEASE.jar!/:2.1.1.RELEASE]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106) ~[spring-boot-actuator-2.1.1.RELEASE.jar!/:2.1.1.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791) [tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417) [tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.13.jar!/:9.0.13]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

**Comment by bzaicsek-cxn** [comment]
Thank you!
I have updated the docker file.
